use serde::{Deserialize, Serialize};

/// Canonical function metadata returned by IDA MCP queries.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct FunctionInfo {
    /// Function start address.
    pub address: u64,
    /// Function name.
    pub name: String,
    /// Optional function size in bytes.
    pub size: Option<u64>,
}

/// Pseudocode generated by decompilation.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DecompileResult {
    /// Decompiled function start address.
    pub address: u64,
    /// Decompiled pseudocode text.
    pub pseudocode: String,
}

/// A single disassembly instruction line.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DisasmInstruction {
    /// Instruction address.
    pub address: u64,
    /// Instruction mnemonic.
    pub mnemonic: String,
    /// Instruction operands as text.
    pub operands: String,
}

/// Cross-reference relation.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct XRef {
    /// Source address of the xref.
    pub from_addr: u64,
    /// Destination address of the xref.
    pub to_addr: u64,
    /// Xref category from IDA.
    pub xref_type: String,
}

/// Basic block in a function control-flow graph.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BasicBlock {
    /// Block start address.
    pub start: u64,
    /// Block end address.
    pub end: u64,
    /// Successor block start addresses.
    pub succs: Vec<u64>,
}

/// Rename request for function-style renames.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RenameRequest {
    /// Address in hex string form.
    pub addr: String,
    /// New symbol name.
    pub name: String,
}

/// Comment request for setting an address comment.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct CommentRequest {
    /// Address in hex string form.
    pub addr: String,
    /// Comment text to apply.
    pub comment: String,
}
