use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
/// Role of a message in a conversation.
pub enum Role {
    /// System message that sets context or instructions.
    System,
    /// User message (input from the user).
    User,
    /// Assistant message (response from the LLM).
    Assistant,
    /// Tool result message containing one or more tool execution outcomes.
    ToolResult,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// A single message in a conversation.
pub struct Message {
    /// The role of the message sender.
    pub role: Role,
    /// The text content of the message.
    pub content: String,
    /// Structured tool results attached to this message.
    #[serde(default)]
    pub tool_results: Vec<ToolResult>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
/// A callable tool exposed to the model.
pub struct ToolDefinition {
    /// Unique tool name used by the model.
    pub name: String,
    /// Human-readable description of the tool's purpose.
    pub description: String,
    /// JSON Schema definition for the tool input.
    pub parameters: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// A tool invocation emitted by the model.
pub struct ToolCall {
    /// Provider-specific tool call identifier.
    pub id: String,
    /// Name of the called tool.
    pub name: String,
    /// JSON input payload for the tool call.
    #[serde(default)]
    pub input: Value,
    /// Raw JSON argument payload when providers stream/return argument text.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments_raw: Option<String>,
    /// Parse error captured while decoding provider argument payload.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parse_error: Option<String>,
    /// Provider name that produced this call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// Provider stream correlation index for this call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stream_index: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// A tool execution result sent back to the model.
pub struct ToolResult {
    /// The originating tool invocation identifier.
    pub tool_use_id: String,
    /// Structured output payload from the tool.
    #[serde(default)]
    pub output: Value,
    #[serde(default, deserialize_with = "deserialize_string_or_default")]
    pub display_summary: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub content: String,
    /// Whether the tool execution failed.
    pub is_error: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
/// Canonical completion stop reasons across providers.
pub enum StopReason {
    /// Model completed its turn naturally.
    EndTurn,
    /// Model stopped to request tool execution.
    ToolUse,
    /// Generation halted at the max token budget.
    MaxTokens,
    /// Generation halted by an explicit stop sequence.
    StopSequence,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// Token accounting for a completion or stream.
pub struct Usage {
    /// Input tokens consumed by the request.
    pub input_tokens: u32,
    /// Output tokens generated by the model.
    pub output_tokens: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// Structured stream event variants for text and tool-calling.
pub enum StreamChunkKind {
    /// Incremental text emitted by the model.
    TextDelta(String),
    /// Incremental JSON input delta for an in-flight tool call.
    ToolCallDelta {
        /// Tool call identifier.
        tool_use_id: String,
        /// Raw partial JSON input fragment.
        input_delta: String,
    },
    /// Finalized tool call payload.
    ToolCallComplete {
        /// Tool call identifier.
        tool_use_id: String,
        /// Called tool name.
        name: String,
        /// Full parsed tool input payload.
        input: Value,
    },
    /// Terminal stream marker with canonical reason and usage.
    Done {
        /// Canonical reason generation finished.
        stop_reason: StopReason,
        /// Request usage metrics.
        usage: Usage,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
/// A request for LLM completion.
pub struct CompletionRequest {
    /// The model identifier to use for completion.
    pub model: String,
    /// The conversation messages to send to the model.
    pub messages: Vec<Message>,
    /// Maximum number of tokens to generate (optional).
    pub max_tokens: Option<u32>,
    /// Sampling temperature for response randomness (optional, 0.0-2.0).
    pub temperature: Option<f32>,
    /// Tool definitions available to the model for agentic execution.
    #[serde(default)]
    pub tools: Vec<ToolDefinition>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// The response from an LLM completion request.
pub struct CompletionResponse {
    /// The model that generated the response.
    pub model: String,
    /// The generated text content.
    pub content: String,
    /// The reason the model stopped generating.
    pub stop_reason: Option<StopReason>,
    /// Number of tokens in the input (if provided by the model).
    pub input_tokens: Option<u32>,
    /// Number of tokens in the output (if provided by the model).
    pub output_tokens: Option<u32>,
    /// Canonical tool calls produced by this completion.
    #[serde(default)]
    pub tool_calls: Vec<ToolCall>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// A chunk of streamed response data from an LLM.
pub struct StreamChunk {
    /// Structured stream event payload.
    pub kind: StreamChunkKind,
    /// Legacy stop reason field (deprecated; use `kind`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<StopReason>,
}

fn deserialize_string_or_default<'de, D>(deserializer: D) -> std::result::Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = Option::<String>::deserialize(deserializer)?;
    Ok(value.unwrap_or_default())
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{
        CompletionRequest, CompletionResponse, Message, Role, StopReason, StreamChunk,
        StreamChunkKind, ToolCall, ToolDefinition, ToolResult, Usage,
    };

    #[test]
    fn constructs_common_types() {
        let req = CompletionRequest {
            model: "claude-3-5-sonnet-20241022".to_string(),
            messages: vec![Message {
                role: Role::User,
                content: "hello".to_string(),
                tool_results: Vec::new(),
            }],
            max_tokens: Some(128),
            temperature: Some(0.1),
            tools: vec![ToolDefinition {
                name: "lookup_func".to_string(),
                description: "Looks up function metadata by address".to_string(),
                parameters: json!({"type": "object"}),
            }],
        };

        assert_eq!(req.model, "claude-3-5-sonnet-20241022");
        assert_eq!(req.messages.len(), 1);

        let resp = CompletionResponse {
            model: "gpt-4o-mini".to_string(),
            content: "hi".to_string(),
            stop_reason: Some(StopReason::EndTurn),
            input_tokens: Some(3),
            output_tokens: Some(2),
            tool_calls: vec![ToolCall {
                id: "toolu_123".to_string(),
                name: "lookup_func".to_string(),
                input: json!({"address": "0x401000"}),
                arguments_raw: Some("{\"address\":\"0x401000\"}".to_string()),
                parse_error: None,
                provider: Some("anthropic".to_string()),
                stream_index: None,
            }],
        };
        assert_eq!(resp.content, "hi");

        let chunk = StreamChunk {
            kind: StreamChunkKind::TextDelta("h".to_string()),
            stop_reason: None,
        };
        assert!(matches!(chunk.kind, StreamChunkKind::TextDelta(_)));

        let _tool_result_message = Message {
            role: Role::ToolResult,
            content: String::new(),
            tool_results: vec![ToolResult {
                tool_use_id: "toolu_123".to_string(),
                output: json!({"status": "ok"}),
                display_summary: "ok".to_string(),
                content: "ok".to_string(),
                is_error: false,
            }],
        };

        let _done = StreamChunkKind::Done {
            stop_reason: StopReason::EndTurn,
            usage: Usage {
                input_tokens: 1,
                output_tokens: 1,
            },
        };
    }
}
